### ISSUE TITLE
블록체인 네트워크 제작

### ISSUE THREAD

**Issue by comstering** [NetworkSecurityLab-2021/BoT#7]
- [x] 사용자 Org
- [x] 아두이노 기기 Org
- [x] 조직별 채널 구성
- [x] 체인코드 작성

**Comment by kmg733** [comment]
남은 과제:
1. 블록체인의 쌓여있는 블록을 열람하는 코드 그리고 그것을 보여줄 홈페이지(FE)
2. IoT 전등의 ip주소를 알아내는 코드 또는 ip주소를 저장하고 그를 처리하는 체인코드 작성
3. 가스 검출기와 온습도 측정기의 데이터를 받을 서버와 그 데이터를 처리할 체인코드 작성
